// Code generated by goctl. DO NOT EDIT.
package types

type AddCommentReq struct {
	ArticleId int64  `json:"articleId"`
	Body      string `json:"body"`
}

type AddTagReq struct {
	TagName string `json:"tagName"`
}

type AddTagResp struct {
	BaseResp
	Data Tag `json:"data"`
}

type Article struct {
	Id             int64    `json:"id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Body           string   `json:"body"`
	TagList        []string `json:"tagList"`
	CreatedAt      string   `json:"createdAt"`
	UpdatedAt      string   `json:"updatedAt"`
	Favorited      bool     `json:"favorited"`
	FavoritesCount int64    `json:"favoritesCount"`
	Author         Profile  `json:"author"`
}

type ArticleListResp struct {
	BaseResp
	Data ArticleListRespData `json:"data"`
}

type ArticleListRespData struct {
	Articles      []Article `json:"articles"`
	ArticlesCount int64     `json:"articlesCount"`
}

type ArticleResp struct {
	BaseResp
	Data Article `json:"data"`
}

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type Comment struct {
	Id        int64  `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Body      string `json:"body"`
	Author    User   `json:"author"`
}

type CommentListResp struct {
	BaseResp
	Data []Comment `json:"data"`
}

type CommentResp struct {
	BaseResp
	Data Comment `json:"data"`
}

type CreateArticleReq struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Body        string  `json:"body"`
	TagList     []int64 `json:"tagList"`
}

type DelCommentReq struct {
	ArticleId int64 `json:"articleId"`
	CommentId int64 `json:"commentId"`
}

type DelCommentResp struct {
	BaseResp
	Data string `json:"data"`
}

type DeleteArticleReq struct {
	ArticleId int64 `json:"articleId"`
}

type DeleteArticleResp struct {
	BaseResp
	Data string `json:"data"`
}

type FavoriteArticleReq struct {
	ArticleId int64 `json:"articleId"`
}

type FollowUserReq struct {
	UserId string `json:"userId"`
}

type GetArticleListReq struct {
	Tag       string `json:"tag"`
	Author    string `json:"author"`
	Favorited string `json:"favorited"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

type GetArticleReq struct {
	ArticleId int64 `json:"articleId"`
}

type GetCommentListReq struct {
	ArticleId int64 `json:"articleId"`
}

type GetProfileReq struct {
	UserId string `json:"userId"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Profile struct {
	UserId    int64  `json:"userId"`
	UserName  string `json:"username"`
	Bio       string `json:"bio"`
	Following bool   `json:"following"`
}

type ProfileResp struct {
	BaseResp
	Data Profile `json:"data"`
}

type RegistrationReq struct {
	UserName string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Bio	  string `json:"bio"`
}

type Tag struct {
	Id      int64  `json:"id"`
	TagName string `json:"tagName"`
}

type TagListResp struct {
	BaseResp
	Data []Tag `json:"data"`
}

type UnfavoriteArticleReq struct {
	ArticleId int64 `json:"articleId"`
}

type UnfavoriteArticleResp struct {
	BaseResp
	Data string `json:"data"`
}

type UnfollowUser struct {
	UserId string `json:"userId"`
}

type UpdateArticleReq struct {
	ArticleId int64  `json:"articleId"`
	Body      string `json:"body"`
}

type UpdatePasswordReq struct {
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdateUserReq struct {
	Email string `json:"email"`
	Bio   string `json:"bio"`
}

type User struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Token    string `json:"token"`
	UserName string `json:"username"`
	Bio      string `json:"bio"`
}

type UserResp struct {
	BaseResp
	Data User `json:"data"`
}
