// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package service_client

import (
	"context"

	"leanr_go_zero/service/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = service.Request
	Response = service.Response

	Service interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

func (m *defaultService) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := service.NewServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
