// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tagModel interface {
		Insert(ctx context.Context, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Tag, error)
		Update(ctx context.Context, data *Tag) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tag struct {
		Id         int64     `db:"id"`          // id
		TagName    string    `db:"tag_name"`    // 标签名
		DelState   int64     `db:"del_state"`   // 删除状态 0：未删除 1：已删除
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
		DeleteTime time.Time `db:"delete_time"` // 删除时间
	}
)

func newTagModel(conn sqlx.SqlConn) *defaultTagModel {
	return &defaultTagModel{
		conn:  conn,
		table: "`tag`",
	}
}

func (m *defaultTagModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTagModel) FindOne(ctx context.Context, id int64) (*Tag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
	var resp Tag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, data *Tag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TagName, data.DelState, data.DeleteTime)
	return ret, err
}

func (m *defaultTagModel) Update(ctx context.Context, data *Tag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TagName, data.DelState, data.DeleteTime, data.Id)
	return err
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
