// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package server

import (
	"context"

	"leanr_go_zero/service/internal/logic"
	"leanr_go_zero/service/internal/svc"
	"leanr_go_zero/service/service"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) Ping(ctx context.Context, in *service.Request) (*service.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
